### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by smurfiez** [petercoles/Betfair-Exchange#3]
Argument 1 passed to PeterColes\Betfair\Http\Client::setMethod() must be an instance of PeterColes\Betfair\Http\string, string given, called in /home/iwon/5V5ESPORT.COM/cron/vendor/petercoles/betfair-exchange/src/Api/Auth.php on line 62 and defined in /home/iwon/5V5ESPORT.COM/cron/vendor/petercoles/betfair-exchange/src/Http/Client.php

`Betfair::init('xxx', 'xxx', 'xxx+');` 

is the code I'm using to initialize.

**Comment by petercoles** [comment]
Which version of PHP are you using?

**Comment by smurfiez** [comment]
PHP 5.6.33

**Comment by petercoles** [comment]
The minimum supported version of PHP is 7.0, which is defined in the composer.json file. Unfortunately you're tripping over a [PHP feature that was introduced in 7.0.0](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) so is incompatible with your version.

You could fork the repo and remove the string type hinting from the Http\Client class, but there are no guarantees that you won't run into other problems. I'd strongly recommend upgrading to PHP 7 if you can - it's way more performant than 5.

**Comment by smurfiez** [comment]
Alright thanks, switched over that part of the script to a server running PHP7 so that's all fine and dandy now.  On a completely unrelated note, is it possible to retrieve odds from the exchange API

**Comment by petercoles** [comment]
It certainly is. You'd use the [listMarketBook](http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/listMarketBook) call in the Betting API.

**Comment by smurfiez** [comment]
Pardon my ignorance but how would I get the odds for a specific event?

**Comment by petercoles** [comment]
You get odds for a market rather than for an event - most events will have multiple markets.

Although markets are always associated with an event, Betfair uses events in some very inconsistent ways. E.g a soccer match is usually an event, but for horse racing a whole day's racing is initially set up as just one event, though more events may be added later for the same race meeting as additional markets are added.

To get your head around this, I recommend just playing with the API and seeing what data you get back. You'll pretty quickly get a feel for how Betfair returns the data available for different sports.
