### ISSUE TITLE
Update to support PHP8 and Guzzle ^7.0.1

### ISSUE THREAD

**Issue by gkurl** [petercoles/Betfair-Exchange#5]
Hi Peter,

I tried adding this to a brand new laravel project (v8.33.1 as of writing) and came across a couple of composer conflicts - I can see you have stated that only php versions >=7.0 and guzzle versions ~6.3.3 will work - is there a technical dependency for these specific versions or is it possible to upgrade to use the latest?

![image](https://user-images.githubusercontent.com/34505859/111674153-9f1a7700-8813-11eb-881b-17666eb31642.png)

Thanks

**Comment by petercoles** [comment]
There was a specific reason not to use Guzzle prior to 6.3.3, but no reason that I know of not to use later versions of PHP and Guzzle and the tests run fine with PHP 8.0.3 and Guzzle 7.3.0. Accordingly the package has been updated to be more permissive when installing with composer, which will hopefully resolve the issues that you encountered. Please let me know.

**Comment by gkurl** [comment]
Hey Peter - sorry for the delay in response. Thank you for getting those changes in. I am however having some trouble getting this to work - in my application environment I'm getting null back on the variable assigned to the call Betfair::init - I've double checked login details naturally and all seems fine, the details are stored in .env and the password I am using has a hash character in it so I thought this may have been the issue but I just escaped all env variables as strings.

I've copied your Auth and Base unit tests also and am unable to connect to betfair api using credentials - I have however succesfully connected using their API-NG tool with the same credentials so I'm not too sure what's going on. Credentials may not be the issue. Upon copying your unit tests and using my env variables I am getting  the below INPUT_VALIDATION_ERROR message:

`1) Tests\Unit\AuthTest::testLoginObtainsSessionToken
Exception: Error: INPUT_VALIDATION_ERROR`

/srv/www/aqml8/vendor/petercoles/betfair-exchange/src/Api/Auth.php:161
/srv/www/aqml8/vendor/petercoles/betfair-exchange/src/Api/Auth.php:96
/srv/www/aqml8/vendor/petercoles/betfair-exchange/src/Api/Auth.php:54
/srv/www/aqml8/vendor/petercoles/betfair-exchange/src/Betfair.php:20
/srv/www/aqml8/tests/Unit/BaseTest.php:16

The same applies for the very first test - which is `testAuthClassInstantiation` - when I `dd` the env variables in the BaseTest class, they are returning false for some reason even though they are assigned and populated as far as I can tell. I'm finding I have to hardcode the variables as opposed to getting them from the .env as trying to call either `getenv` or `env` always returns null or false for the variable value.

Could you shed any light on this? This is just on the initial step of getting the session token. It's a little bit strange as I'm not getting any HTTP error codes back from the API itself - my application however is returning 200 meaning it's reaching the point where it needs to init but the init call is returning null.

Also this may be code editor related but when using the `Betfair` moniker and calling methods such as `Betfair::init` - phpstorm claims that this method can not be found. Not to sure if this is helper related or not. 

UPDATE: so I've found using `Betfair::auth()->login` returns the session key as expected - but still getting `null` back for `Betfair::init` as per the README. I'm interested in using both.

**Comment by petercoles** [comment]
If I understand correctly, you've both tried running the tests and experimented with ```Betfair::auth()->login``` and ```Betfair::init``` from within a Laravel app.

When you run the package from within a Laravel application, Laravel loads your environment variables, such as your Betfair credentials, from your .env file. However, this isn't a Laravel package - though it can certainly be included in a Laravel app, which is how I use it.

Rather it's a standalone PHP package that could be included in any PHP project using composer, so while it expects the Betfair credentials to be available as environment variables, it's the application's responsibility to make them available (which again Laravel will do for you in normal running).

When running phpunit in Laravel, Laravel extends the base test to load the application, part of which is importing the environment variables. But since this is a stand-alone package, Laravel isn't loaded by the tests and so isn't available to do that for us. Instead the package's BaseTest class assumes they will be loaded by phpunit from your phpunit.xml file. There's a phpunit.xml.dist file to use as a skeleton, and some explanation towards the bottom of the readme file.

When running ```Betfair::auth()->login``` from within Laravel, with proper credentials, you should, and appear to be seeing a session token. When running ```Betfair::init``` you're not, but I wouldn't expect you too, since the package stores the session key and uses it internally, there's no need to pass it back to the user. The only reason the ```Betfair::auth()->login``` method does is to provide a route for users to manage the session token for themselves, but this isn't recommended.

**Comment by gkurl** [comment]
This makes sense - apologies I knew I had a feeling I may have missed something - just checked the README and the phpunit explanation plus your explanation put together have cleared things out. `Betfair::auth()->login` in this instance will be needed as I will be storing the session token in a Database - so when you say not recommended do you have alternatives or have I misunderstood? As the README suggests using `auth()->persist` followed by `auth()->login` if no token is present is what I was planning on doing once the session token has been stored.

Also from a quick search on the Betfair docs - it is suggested that token expiry is 24 hours? Could I double check with you that this is correct - as looking at the code it's suggested that it's 4 hours. If I wanted to check if a login with a session token is still valid how can this be achieved? This is so perfomance can be optimised and unnecessary logins mitigated.

**Comment by petercoles** [comment]
If I remember correctly, sessions timed out after 4 hours when I wrote the package originally, but you are right, this is now 24 hours. However, login is very quick and never bothered me performance-wise, the keep alive call is even quicker.

When using with Laravel I bound the class as a singleton instance in a service provider, making it available for multiple calls and the keepalive session extensions built into the init method allowed long running scripts to keep running without interruption.

This combination of low overhead for logging in, and init's ability to decide whether to login or simply extend an existing session to spend my time on writing trading software rather than maintaining the connection, which is why I recommended that approach.

However, I did have occasions when I was making infrequent calls and didn't want a script running continuously, hence the login and and an approach similar to that I suspect that you're planning, tough then I used Laravel's caching mechanism rather than a database for persisting the session token between calls.

Just as an aside, although I have some older scripts still running using this package, new ones are now written in python. After some 14 years as a PHP developer (and still use it for web development), I crossed over to a language that is better suited to the data science, machine learning and AI that are useful for sports trading, and write new scripts using the awesome BetfairLightweight and Flumine packages.

**Comment by gkurl** [comment]
Yes essentially I'm building a web app which will be able to perform betting related actions for multiple users using one single app key- so I'm thinking some sort of registration/login process to create a user object and then login to betfair for that user - still trying to figure out the best way to do this as I'm not sure if this is the best approach - and whether it's a sign-up process that can be created that streamlines into the betfair login process whilst still being able to retain individual user information and session information - it would possibly mean having to store betfair account information within the application securely - if you've maybe experimented with this sort of thing any pointers would be appreciated. 

I think I may be able to play around with the Init call - essentially I will try and adapt this to be able to have an effective session management process for multiple users. Am I correct in thinking that if Init returns null it means it's triggered the keepAlive command and if not then it returns a session token? I could maybe use this to decide when to create an entry in a betfair_session table or similar.

Would it be possible for you to update the session time to 24 hours to align it with the current API timeout as opposed to 4 hours as it was before?

I think Python is excellent - although not quite what I would require for my project in particular it's something I've been meaning to pick up so will definitely do so going ahead.

**Comment by petercoles** [comment]
Betfair has an interactive login process whereby their login screen is embedded on your site, so that you never see the user's Betfair credentials. I'm pretty sure that if Betfair spotted you saving and then using the user's credentials on their behalf, they'd cut you off in a heartbeat. Another issue with bypassing their recommended approach by accessing Betfair as your users would be that all those users would need to have API credentials, for which Betfair charges.

An alternative and quite popular approach sometimes used (don't know if Betfair offer this - haven't seen it but haven't looked), is where the user visits the service provider (Betfair) and authorises a connection to an intermediary (you), who is issued a token that allows them to login or access data the user's data on the service provider's site. This allows the user to visit service provider's site later and revoke the intermediary's access, and so is safer for both user and service provider.

**Comment by gkurl** [comment]
You raise a very good pont - I'll scrap that idea immediately in that case. I was looking into the interactive login "Desktop Application" method - and the only issue was that the redirect URL takes you to the betfair site - the inability to redirect back to the application is what I was a little confused by. Their documentation states "By default only https://www.betfair.com will be allowed". 

I've had a quick look and I believe the way you are referencing or the closest I could find anyway would be this:

https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Vendor+Services+API#VendorServicesAPI-vendorwebapi

Maybe this is the way forward instead. I've only had a skim read, but if authorised, I'm assuming then actions can be made using your API wrapper in one way or another.

Could the vendor API be used in conjuction with say the API wrapper to retrieve things like odds and make bets on users behalf - I assume this is what the vendor service allows.
